### ISSUE TITLE
JsonResult的问题

### ISSUE THREAD

**Issue by wbcbaochun** [InfogreatFrameworkTeam/bkr.base#1]
1. data请用泛型，这样可以有强类型的好处。既：`JsonResult<T>`
2. 构造函数没有覆盖最常用的场景。
    最常用的是：1）仅返回数据，结果是正常并不设消息 2) 仅返回正常，不设消息不设返回数据
3. 后端尽量不要设消息，消息是表现层的内容尽量让前端来决定，所以默认时仅设code不设消息。

**Comment by chengd1983** [comment]
已对应,请确认！

**Comment by chengd1983** [comment]
已对应，确认！。
